# Generated by Django 5.1.2 on 2024-10-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "VENDOR"), (2, "Customer")], default=2
            ),
        ),
    ]
